### ISSUE TITLE
scalelite-recording-importer not reconnecting database

### ISSUE THREAD

**Issue by christmart** [blindsidenetworks/scalelite#239]
After a restart of our postgresql server holding the scalelite database the scalelite-recording-importer stopped to work, 
because it did not reconnect to the database. Other services like scalelite-api and scalelite-poller worked without problems after the restart, but the importer had to be restarted.

ERROR -- : Failed to import recording: PG::UnableToSend: no connection to the server

On this error it should try to reconnect.

**Comment by farhatahmad** [comment]
I've been seeing this issue multiple times, but haven't quite had time to look into it. The temp solution is to just restart Scalelite and it reconnects correctly

**Comment by defnull** [comment]
The `Listener` callback in `recordings.rake` logs, but otherwise ignores any errors that might happen during an `RecordingImporter.import` call (e.g. database errors). I am not sure yet if it really completely stops processing recordings after that, or if it just skips the recordings that failed. In any case, you'd end up with unprocessed recordings in the spool directory. Only a restart helps.

Suggestion: The current implementation first looks for existing tar-files in the spool folder and processes them all, then start the listener to process new files as soon as they are created. After the first scan it just sleeps indefinitely in the main thread and all work happens in the file-change listener thread. How about: Loop in the main thread with a short sleep (N seconds) and check for tar files to process in every loop. In addition, use the listener interface to find new tar files quicker. Protect the processing with a lock to avoid races. This way, jobs that fail in the listener thread are re-tried every N seconds in the main thread.

Or even simpler: Process recordings in the main thread only, in an infinite loop that waits for a `Concurrent::Event` with a short timeout. The `Listen.to` callback just sets the event, that's all. As soon as a file is added and the `Event` is set, or the `Event.wait` timeout on the event runs out, the main-loop globs all files it can find and processes them in order, logging but ignoring any errors. Best of two worlds: Immediate handling of new files, and free infinite retries on files that did not process for some reason. You could even scrap the `Listen.to` completely and just glob the spool directory every 5 seconds. That directory should be empty most of the time, so accessing it every 5 seconds is no real overhead at all. Sometimes the simple solution is best.

**Comment by defnull** [comment]
Pseudocode (I'm not a ruby developer):
```ruby
    new_stuff = Concurrent::Event.new

    listener = Listen.to(dir, opts) do |_modified, added, _removed|
      new_stuff.set unless added.empty?
    end
    listener.only(/\.tar$/)
    listener.start

    loop do
        Dir.glob("#{dir}/*.tar").each do |file|
            RecordingImporter.import(file)
        rescue StandardError => e
            Rails.logger.error("Failed to import recording: #{e}")
        end

        new_stuff.wait(5)
    end
```

**Comment by TeachReo** [comment]
I would like to know how the users who have the same problem like me on #337 ran their meetings ?
I use the moodle connector and I seen some differences between the files where the import run without problem and the others don't. I search to determinate where the problem come from. In my case the problem it's not the database because recording before and after are published correctly.

**Comment by defnull** [comment]
The front-end (moddle/geenlight/...) should have no impact. The recordings are generated by BBB. The tar archive that is moved to Scalelite is generated by the scalelite provided `scalelite_post_publish.rb` script (or whatever you installed to the BBB servers).

**Comment by TeachReo** [comment]
yes, but how you can explain in the tar archive the recording is complete, and not to the import ? I thought the problem came from metadata.xml file but it comes after the extract, normally...

**Comment by bklein1** [comment]
Do you have a list of versions that are affected by this bug?
