### ISSUE TITLE
Better balancing function - feature request

### ISSUE THREAD

**Issue by xpolish** [blindsidenetworks/scalelite#338]
Hello,

now scalelite opens new meeting session on server with lowest result of (load_multiplier * num_of_running_rooms). My proposal is extend this function to (load_multiplier * num_of_running_rooms * square_root( number_users )). 

My load is:
    HOSTNAME     STATE   STATUS  MEETINGS  USERS  LARGEST VIDEOS 
 bbb                      enabled  online         5                63              36          2 
 bbb2                    enabled  online         4                12              6            0 
 bbb3                    enabled  online         4                56              20          2 
 bbb4                    enabled  online         4                83              44          1 
 bbb5                    enabled  online         2                117            99          0 
 bbb6                    enabled  online         4                321            153        1 
 bbb7                    enabled  online         3                108            101        0 
 bbb8                    enabled  online         3                54              42          2 
 bbb9                    enabled  online         3                39              16          6

    Thank you  Pavel Polacek

**Comment by defnull** [comment]
The number of users that will join a new meeting cannot be known in advance, and users may not join immediately after the meeting is created. There is a short time where the 'weight' of a new meeting is lower than it will be in a couple of minutes, and you cannot know how heavy it will get. This introduces a problematic effect: If one server has a certain head-room compared to the others (e.g. because a large meeting ended), and multiple new meetings are created in a short time-span, then that server will get an unproportionally large number of these new meetings. Think about lectures that all start at the same time. They are 'cheap' as long as they are empty, so they may all end up on a single single server. This effect gets worse the more you weaken the meeting-count impact.

The current balancing algorithm is not perfect, but it is fair. It only gets unbalanced if multiple large meetings end up on the same server, but that's just bad luck and cannot be known in advance. Your proposal weakens this fairness, but keeps the risk of multiple large meetings ending up on the same server. I'm not sure if this is really an improvement.

**Comment by xpolish** [comment]
Hello defnull,

  I see. I didn't want  to change complete meaning of balance algo, only extends it in style:"if you have same servers with same number of running rooms => use/prefer servers with lower count of users". Square root was first function in mind, As I understand we need function that generate number between 1.0 and 2.0 (lower than typical number of running rooms), that leaves num_of_running_rooms most important value in expression.  Maybe user_multiplier = num_of_actual / 1000 + 1 (so 10 user will be 1.01, 100 users will be 1.1, 300 users will be 1.3). 

    Thank you  Pavel

**Comment by matiasilva** [comment]
I know there's been talk about better algorithms in some other issue, so @defnull what would be your ideal algorithm?

**Comment by farhatahmad** [comment]
Theres already been alot of talk in this in #99
