### ISSUE TITLE
Old recordings are not displayed in Greenlight, but there are accessible

### ISSUE THREAD

**Issue by parreitu** [blindsidenetworks/scalelite#364]
Nowadays we are working with a BBB installation with an unique server, so I'm setting up a new installation with new servers and scalelite.  I have been able to install scalelite, and it works correctly.

After installing Greenlight, I've migrated the old Greenlight database copying the whole Greenlight folder (https://github.com/bigbluebutton/greenlight/issues/1567), so in the new Greenlight I can see all the users, rooms, etc, that I have in the old installation.

The problem is that I cant see the old recordings in the Greenlight interface. The new recordings are visible, but not the old recordings. Curiously, if I build the URL appending the recording ID (folder name into /mnt/scalelite-recordings/var/bigbluebutton/published/presentation/) of an old recording, I can see it, so apparently is not a permission issue.

The only problem is that Greenlight is not showing the recordings

Any suggestion ?

Thanks in advance.

**Comment by matiasilva** [comment]
Yeah, because you have to migrate the old recordings to Scalelite. Scalelite stores its own copies of recording info so it can know to which server it must redirect requests to. This is in the documentation.

**Comment by parreitu** [comment]
Hi @matiasilva 

I've migrated the old recordings to the new scalite server (https://docs.bigbluebutton.org/2.2/customize.html#transfer-published-recordings-from-another-server), so I can access to the old recordings using the new scalelite server as I can access to the new recordings. For example, if I've this recording in the old server bbb server:

https://bbb.mydomain.com/playback/presentation/2.0/playback.html?meetingId=3f229f9620462983bcc76a86e6c62e418bd1dc5-1604597513282

And I can access to the same recording in the new server:

https://scalelite.mydomain.com/playback/presentation/2.0/playback.html?meetingId=3f229f9620462983bcc76a86e6c62e418bd1dc5-1604597513282

I'm comparing the new recordings and the old recordings folders in the folder /mnt/scalelite-recordings/var/bigbluebutton/published/presentation , but the permissions are the same.

With Moodle I've the same problem. New recordings appear in the activity but old recordings not. Also, all the recordings (old and new) are stored in /mnt/scalelite-recordings/var/bigbluebutton/published/presentation/ with the same permissions ....

Thanks !!

**Comment by parreitu** [comment]
I think I know what is happening 

There is a table in the scalelite postgresql database named recordings. If I make a "select * from recordings;" I can see only records of the new recordings, but not the imported recordings. 

I guess that the import process should add records in this table, but I've not found information about that table in the documentation.

Any advice ? 

Thanks

**Comment by matiasilva** [comment]
As per the documentation: https://github.com/blindsidenetworks/scalelite/blob/master/sharedvolume-README.md#configuring-the-bigbluebutton-recording-transfer, you must run the recording import script to rsync the recordings to the spool directory, so that the recording poller can find it and add the respective entry to the database.

> There is a table in the scalelite postgresql database named recordings. If I make a "select * from recordings;" I can see only records of the new recordings, but not the imported recordings.

That's what I meant in my previous comment:

> Scalelite stores its own copies of recording info so it can know to which server it must redirect requests to. This is in the documentation.

**Comment by abonadt** [comment]
@parreitu 
The import script and the scalelite-recording-importer copies the presentations from old servers to scalelite server and fills up the recordings table in the scalelite database. But the recordings are not displayed in the admin view.

I think it is because the recordings table entries have no counterpart in the room (=meeting_id) table of the new greenlight database.

I am also looking for a solution for merging room and user tables from my 7 old BBB servers into the new greenlight database. I am afraid this will not be an easy task.
