### ISSUE TITLE
Scalelite with Moodle - unbalanced load distribution

### ISSUE THREAD

**Issue by glu000** [blindsidenetworks/scalelite#401]
I used these instructions to setup a scalelite server and did not change any default values or paths: https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6

I setup 2 BBB servers and use the BBB-Moodle plugin as frontend (latest version)

In general everything works fine. When there is no load on both servers and I start the BBB-activity in Moodle, the rooms are opened alternately on the servers as expected. But sometimes it seems, that the load distribution is not balanced. See 2 screenshot below. Between 10:15 and 11:40 there are only 3 rooms in the first server. At 10:15 there are already 13 rooms on the second server, so I would expect, that new rooms will be opened on the first server. But new rooms are still created on the second server, which leads to a significantly higher load on the second server than on the first server.

The configuration of the 2 BBB-servers is identical. In Scalelite both servers have the same load-multiplier. Scalelite shows both servers as enabled and online. Scalelite status shows the same number of rooms / users than Grafana (which is used to monitor both servers) 

Any ideas what could be wrong or how to debug this issue?

<img width="1784" alt="Bildschirmfoto 2021-01-17 um 12 15 33" src="https://user-images.githubusercontent.com/25256186/104838997-c6f66880-58be-11eb-864d-476a05b08aae.png">

<img width="1784" alt="Bildschirmfoto 2021-01-17 um 12 16 15" src="https://user-images.githubusercontent.com/25256186/104839005-cfe73a00-58be-11eb-847e-eb971fee8a9c.png">

**Comment by PhMemmel** [comment]
At 10:15 you have a sudden raise of +4 rooms. This is very unlikely to be 4 users creating 4 new separate meetings, this is more likely to be the creation of breakout rooms which of course is happening on the same server (scalelite isn't handling breakout rooms). In the time interval 10:00 to 11:00 all room changes appear to be breakout room related (every time sudden change of number of rooms by more than 1).

Unbalanced loads like this can happen because of the basic problem that it's impossible for scalelite to know how big a meeting is going to grow at the time of creation.

If you wanna understand, why a session is being opened at one or the other servers, do a `./bin/rake servers` to see the current load value of your servers.

Another problem can be the polling interval: scalelite by default only checks the server status every 30s IIRC. So if you have typical timeslots where meetings are getting started and grow fast (begin of lessons according to timetable at a school for example), you might wanna try lowering that polling interval so scalelite has a more accurate information basis on which it can decide where to distribute the new meetings to.

This issue is most likely nowhere related to moodle IMHO. BTW: I don't think it's a scalelite issue at all.

**Comment by glu000** [comment]
Thanks for your response - this makes sense. I'l try to reduce the polling interval to 10sec

**Comment by farhatahmad** [comment]
Agreed with the response above, but the culprit is not likely to be the polling interval. Scalelite also adjusts the load anytime a new meeting is created, and then rechecks it during the polling process. This is most likely due to breakout rooms
