### ISSUE TITLE
Scalelite Api URL not conformant with that of BigBlueButton server

### ISSUE THREAD

**Issue by pielonet** [blindsidenetworks/scalelite#423]
Hi,
It looks like Scalelite's actual working API URL is in the form 'https://scalelite.example.com/bigbluebutton/api' although it should be in the form 'https://scalelite.example.com/bigbluebutton/' as stated **wrongly** in the official documentation here (https://github.com/blindsidenetworks/scalelite#configure-your-front-end-to-use-scalelite).

You can test it here :
https://arawa-test-bbb-scalelite.infra.arawa.fr/bigbluebutton/api WORKS
https://arawa-test-bbb-scalelite.infra.arawa.fr/bigbluebutton/ FAILS

This is not a problem for the Greenlight frontend nor for Moodle Plugin since both accept Endpoint URLs in this long "/bigbluebutton/api" form.

But it IS a problem with Nextcloud's BBB integration plugin which only accepts URLs in the short "/bigbluebutton/" form.

**Comment by sebastianberm** [comment]
@pielonet 
Not entirely sure about this. We've got Scalelite working with the Nextcloud BBB integration for one environment. Although, the /api/ is required, but that's also the case for other environments. 

To give an idea;
The default URL for the Moodle plugin is http://test-install.blindsidenetworks.com/bigbluebutton/ according to the demo settings.

But this gives a nice 404 error, from Nginx, because the actual URL is http://test-install.blindsidenetworks.com/bigbluebutton/api/.

So it's probably better to open up a ticket at the Nextcloud plugin and ask them to add /api/ to everything.

**Comment by farhatahmad** [comment]
Hmm Yeah I'm not quite sure this is a Scalelite issue. Greenlight and Moodle both append `/api` to the end of the `SERVER_ENDPOINT` which means the correct url is `https://scalelite.example.com/bigbluebutton/api`. We'll update the docs to better reflect that, but I'm sure there's anything else we can do
