### ISSUE TITLE
Multiple vulnerabilities in Ruby on Rails - CVE-2021-22880 CVE-2021-22881

### ISSUE THREAD

**Issue by aguerson** [blindsidenetworks/scalelite#431]
```
    https://groups.google.com/g/rubyonrails-security/c/zN_3qA26l6E


    https://groups.google.com/g/rubyonrails-security/c/ZzUqCh9vyhI

    CVE CVE-2021-22880
    http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22880

    CVE CVE-2021-22881
    http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22881

```

**Comment by sebastianberm** [comment]
Scalelite isn't affected by http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-22880, if not mistaken. The money type isn't used :-)

The other one is interesting, not 100% sure, but I don't think Scalelite is affected due to the fact you need a valid FQDN to be set as 'URL_HOST' environment variable.
A valid FQDN cannot start with a ., so I doubt if Scalelite is affected.

**Comment by amalrails** [comment]
closing this issue since Scalelite isn't affected by the vulnerabilities.
