### ISSUE TITLE
We could not find a meeting with that meeting ID...

### ISSUE THREAD

**Issue by GXiangCo** [blindsidenetworks/scalelite#438]
**We used the latest version of**

- blindsidenetwks/scalelite:master-api (sha256:f52c531e14168c38b51acc73208c1ccf281331c5145a9b708f4fafc78c520bbd)
- blindsidenetwks/scalelite:master-nginx (sha256:55a8cd42db9739d2477b512dc6d143d75a9cd3d975a9cabb411ffb647077444a)
- blindsidenetwks/scalelite:master-poller	(sha256:55c0faed55b566a2fea4e51df59fc2f1027a13a3bb595b08455116f7e445cc72)
- blindsidenetwks/scalelite:master-recording-importer  (sha256:fc2243d186545be4a4c3106f7ecd6d201fa4323d77d3e4dc5e5d9912d4b99914)

**then received the following FAILED messages:**

```
<response>
<returncode>FAILED</returncode>
<messageKey>notFound</messageKey>
<message>We could not find a meeting with that meeting ID - perhaps the meeting is not yet running?</message>
</response>
```

Althought when we used the older versions everything is working well.

The front-end : Moodle
BigBlueButton : v2.2.31

Is the any solution to figure it out these issues?

**Comment by GXiangCo** [comment]
new Version is OK!

**Comment by GXiangCo** [comment]
V1.0.9 get the same problem....

```
<response>
<returncode>FAILED</returncode>
<messageKey>notFound</messageKey>
<message>We could not find a meeting with that meeting ID - perhaps the meeting is not yet running?</message>
</response>
```

**Comment by PhMemmel** [comment]
Same here, a fast look at the scalelite-api tells me that this issue might be related to the polling process:

After the upgrade to v1.0.9 (and after fixing the problem which was already adresses bei #451 ;-)) scalelite-API appears to be running fine, most rake tasks are looking good.
However, when trying `rake poll` scalelite apparently has some issues: I couldn't find out what exactly is the problem, I just had a quick look and was then forced to get the scalelite back up and running again by downgrading back to v1.0.8, but there were hundreds of messages running infinitely over my screen instead of the expected "poll meetings -> show polled meetings -> wait -> poll again" process. Maybe this is related to the problem with the not found sessions. Servers and count of meetings (the one which can be accessed) are showing fine in the `rake servers` and `rake status` tasks. Polling the servers separately doesn't seem to be an issue as well.

**Comment by Davka** [comment]
Try set POLLING_INTERVALL in /etc/default/scalelite

https://github.com/blindsidenetworks/scalelite/pull/428

**Comment by jfederico** [comment]
You can pull from master, the patch has been merged. We'll do a hot-fix release in the next hour
