### ISSUE TITLE
Scalelite is not creating new meeting-room for stored meetings if the 'original' server is not available

### ISSUE THREAD

**Issue by makabar** [blindsidenetworks/scalelite#489]
To reproduce it:
create a meeting room 'testmeeting' in greenlight.
start the meeting. meeting starts on bbb1.example.com. close the meeting.
shut down bbb1.example.com. 
try to start 'testmeeting' again. in according to my opinion the next meeting in this room should start on next - server bbb2.example.com or something like that.
but greenlight gets an key-error because bbb1.example.com is not available.

**Comment by ichdasich** [comment]
Might be related to #202

**Comment by amalrails** [comment]
@makabar the problem here is the meeting in scalelite is still mapped to the offline server and hence join request fails. 
Since the join request wouldn't have all the parameters which are used in a create action, it would require a big design/code change to handle this issue. So it cannot be implemented right now but we take it up in future.
