### ISSUE TITLE
Scalelite v1.0.12.1-bionic230-alpine template files are in the wrong directory

### ISSUE THREAD

**Issue by ThomasScheuemann** [blindsidenetworks/scalelite#523]
Tried the v1.0.12.1-bionic230-alpine extended docker container for Scalelite and it would not start.

Turns out in scalelite-nginx /etc/nginx/start is loading the template files from /etc/nginx/conf.d

But actually all template-files are in /etc/nginx and copying the correct one to /etc/nginx/conf.d/scalelite.conf makes the container start.

**Comment by jfederico** [comment]
How are you deploying? with systemd?

**Comment by ThomasScheuemann** [comment]
I'm using the "Lazy Deployment" via docker und just set "SCALELITE_TAG" to "v1.0.12.1-bionic230-alpine".
"docker-compose up -d" will start all containers, except that inside the "scalelite-nginx" nginx would not run because the config files were not complete.

**Comment by jfederico** [comment]
Yeah, that is what I though. The issue is not related to scalelite but to the deployment itself. And I have not updated that script.

The problem is that on alpine 3.13 conf.d is no longer a directory but a symbolic link pointing to http.d.

You would only need to copy the files to http.d instead. I have not tried with docker-compose but that is what happen when we updated the images.

Starting with this version there is a better way to install all this with docker. And we are going to change the recommended deployment starting on 2.0. You can take a peek here https://github.com/jfederico/scalelite-run/blob/develop/docker-compose-dev.yml

But keep in mind that there is no magic bullet on this kind of deployments. You need to know what you need and how is done in order to get a proper set up.
