### ISSUE TITLE
Not all recordings visible

### ISSUE THREAD

**Issue by ZAZmaster** [blindsidenetworks/scalelite#537]
When i use Greenlight -> Latest Recordings - i see only 25 recordings (no pagination) but through API getRecordings i see all (about 150 recordings). Its Greenlight problem or Scalelite?

**Comment by jfederico** [comment]
This is not an "issue" (meaning bug). It is like that by design because when there are so many recordings linked to a room, the request times out. The query it is much more efficient if you use SL, but the change was made to GL to improve performance. 

I think you can filter recordings and that may give you what you are looking, but you need to know some keyword such as name or description.

But you have the answer, if your getRecordings respond with 150 recordings (which is crazy), it means that it is entirely on Greenlight. You may be of better luck by asking in the mailing list or opening an issue in GL.
