### ISSUE TITLE
Server for Panic

### ISSUE THREAD

**Issue by mauser8004** [blindsidenetworks/scalelite#544]
Would it be possible not to display the "This session has ended" tab? It's a "Please Rejoin" tab. Probably BBB developers should also be consulted.

**Comment by amalrails** [comment]
@mauser8004  It cannot be done from scalelite

**Comment by jfederico** [comment]
If you panic the server, you want users to go back tot he 3rd party application, create a new meeting or join the newly created one instead of the old one. So, it will never be a re-join.

And it is not even a BBB issue. BBB is doing exactly what it is expected.

What is exactly the case you are trying to cover? Describe the whole situation.

**Comment by jfederico** [comment]
Hi @mauser8004 

I see your case. But as Amal mentioned before, as it is right now, there is nothing we can do from SL.

When you panic a server 3 things happen.
1. Disabled the BBB server
2. SL sends an endMeeting request to BBB for all the current meetings
3. Clears all the meetings from SL cache

These are the steps you would normally do even if you were doing it manually. It is just saving you time and giving the proper order to optimize the results.

So, for BBB it is just an endMeeting request. It won;t handle it differently because it does not know the reasons why the meeting was forcibly ended. So, you can imagine the answer from the developers of the BBB project :)

Now, your concern is right. There should be a way to notify the user differently in cases like this. It is just that we don't have the means for doing it right now.

Ono thing that crosses my mind is that BBB could have the way to handle "endMeeting requests with a message", so, if a message is included as part of the parameters, that would be the message to be displayed in the client. Or even better "endMeeting with a code" so the message is standard and localized.

I can ping the guys currently maintaining the API and the HTML client, but that is all I can do for now.

I'll close this ticket as there is no much to do in terms of this project.

**Comment by mauser8004** [comment]
Thank you very much!!!!
