### ISSUE TITLE
connect with bigbluebutton docker

### ISSUE THREAD

**Issue by harithadias** [blindsidenetworks/scalelite#596]
how can we connect scalelite with bigbluebutton docker installation

**Comment by amalrails** [comment]
@harithadias i am assuming you mean, how to add a server to scalelite? https://github.com/blindsidenetworks/scalelite#add-a-server, here's the link to that.

**Comment by harithadias** [comment]
@amalrails no.I am installed the bigbluebutton docker version. https://github.com/bigbluebutton/docker

**Comment by jfederico** [comment]
@harithadias I don't understand your question but I'll do my best on guessing.

You install Scalelite in a separated machine following the steps in the README. Once you have that, you only need to add the bigbluebutton server (or servers) to Scalelite. Indtructions are also in the README.

As long as you can access the BBB API (https://yourserver/bigbluebutton/api) server from the SL server using CURL or WGET, you should be fine.

The only information you need in order to add a BBB server to SL is the URL and Secret (that is also in the README)

Is am going to close this issue as this is not development related.
