### ISSUE TITLE
Servidores bbb's agregados al scalelite desaparecen al pasar unas horas.

### ISSUE THREAD

**Issue by WinterJV** [blindsidenetworks/scalelite#617]
Hola buenas tardes, quisiera saber si me podrían ayudar con este inconveniente:( al agregar los servidores bbb al scalelite para que realicen su funcionamiento de redireccion funciona perfectamente, pero al pasar unas horas desaparecen.

docker exec -i scalelite-api bundle exec rake servers:add[https://bbb.exampple/bigbluebutton/api/,secret]

Por lo que veo cuando no hay nadie en el servidor los desaparece a las horas pero cuando hay alguien los deja ahi. 

Revise la persistencia de redis realizando la configuración de appendonly "yes" y posteriormente reiniciando el servidor, al iniciar vuelvo agregar los servidores bbb y dirigirme al redis-cli aplicando bgsave para guardarlos, pero aun asi los sigue desapareciendo:(

Podría reemplazar redis por nada mas utilizar swap o es a fuerza la utilización de redis ?

Se evitaría el inconveniente si no utilizo redis en el mismo servidor ?

Si me pudieran apoyar se los agradecería un montón!.

**Comment by jfederico** [comment]
@WinterJV first of all, this project is managed in English. Even though some of the people here is able to understand you, we keep it in the intended Language. Please make sure to ask your questions in English.

If I understand clearly, the Servers added to SL should not just disappear. You may have an issue with persisting the redis database, but that is a configuration issue.

Now, regarding your questions. 

No, you cannot replace redis with anything else. The database of choice for the live events is redis.

Using redis in a different server or instance is something we always recommend for production. But the problem is unrelated to that.

You could try using scalelite-run for development. That runs redis and postgres using docker in the same host machine and both are configured in the way you need so the data is persisted.
