### ISSUE TITLE
Scalelite session can't start by moodle: We could not find a meeting with that meeting ID

### ISSUE THREAD

**Issue by MrCapitalist** [blindsidenetworks/scalelite#636]
Hi
I have Scalelite docker containers in the following version:

```
docker ps:

blindsidenetwks/scalelite:v1.1.7-bionic230-alpine-recording-importer
blindsidenetwks/scalelite:v1.1.7-bionic230-alpine-nginx
blindsidenetwks/scalelite:v1.1.7-bionic230-alpine-poller
blindsidenetwks/scalelite:v1.1.7-bionic230-alpine-api
redis
postgres
```

I also use Moodle to manage my sessions and courses. Everything (classes) is OK but only one of my BBB classes can't start by load balancer!
In this class, when I click join room, the following error show to me:

```
<response>
<returncode>FAILED</returncode>
<messageKey>notFound</messageKey>
<message>We could not find a meeting with that meeting ID - perhaps the meeting is not yet running?</message>
</response>
```

Note that If I change the URL/Secret key in Moodle > BigBlueButton plugin to a single server URL/Secret, it will be ok and start without any problem!! 

How can I fix this class?
Thanks

**Comment by MrCapitalist** [comment]
I think I must edit the database or its cache and clean open meetings. Can anyone help me?

**Comment by renanrmelo** [comment]
Hello, I'm with the same problem. Whats versions of the BBB are you using?

**Comment by jaimemejia** [comment]
I had similary error with one BBB server.

If i not remember bad, my procedure to solve it was:

1. Panic the server on Scalelite.
2. Check the logs of scalelite-api container. In the logs you can find what the meeting was not found (copy the meeting id).
4. Enter on redis-cli and delete the key with this patern: scalelite:meeting:[meeting-id]

And after delete the key on redis the problem was solved.

I hope that my experience helps you to solve your problem. Greetings

**Comment by renanrmelo** [comment]
Thanks @jaimemejia 

I did this yesterday and solved the problem.

Thanks.

**Comment by jfederico** [comment]
Thanks for helping us to track this down @jaimemejia. We are considering to make a modification to the poller to take care of this automatically. It would be part of the first revision of the next version, soon to be released.
