### ISSUE TITLE
init-letsencrypt.sh

### ISSUE THREAD

**Issue by mortazan** [blindsidenetworks/scalelite#672]
I was using his installation for the past 1 year, now when i tried to deploy it in a new machine, i get the following error while executing ./init-letsencrypt.sh.
WARNING: The RAILS_LOG_TO_STDOUT variable is not set. Defaulting to a blank string.
Generating a RSA private key
........................................................+++++
...........+++++
writing new private key to '/etc/letsencrypt/live/xyz.school.co,redis./privkey.pem'
-----
### Starting scalelite-nginx ...
WARNING: The RAILS_LOG_TO_STDOUT variable is not set. Defaulting to a blank string.
ERROR: No such service: scalelite-nginx

**Comment by jfederico** [comment]
You don't have the variable defined in your .env file, you either add it set to `true/false` or assign a value by default in your docker-compose.yml file https://github.com/jfederico/scalelite-run/blob/master/docker-compose.yml#L79

You can create the SSL certificates in a different way though. You don't need to use that script

Either way, this issue is unrelated to scalelite. But to the non-maintained helper scripts scalelite-run.
