### ISSUE TITLE
Recordings V0.9.0 slides cannot be played anymore

### ISSUE THREAD

**Issue by jjvanrossum** [blindsidenetworks/scalelite#721]
**Describe the bug**
When playing a recording made in BBB-version 0.9.0 the slides are not loaded properly

**To Reproduce**
Not sure how to reproduce other than with a V0.9.0 recording with slides

***Deployment:***
1. Deployment: Docker compose
2. Versions: pfew, don't know how to get that out of the setup, but definitely one of the latest. We updated two weeks ago..
3. Tools used for reproducing the issue: browser inspect tool in chrome

***Steps to reproduce the behavior:***
1. Playing a V0.9.0 recording with slides
2. No slides on the left slide-pane and no active slide in the main pane

**Expected behavior**
-

**Screenshots**
-

**Additional context**
I already narrowed down the issue. The slides are loaded from an SVG, and JavaScript expects the documenttype to be XML. Somehow this has changed recently to be not accepted anymore; see https://blog.yeshere.org/2010/11/xmlhttprequestresponsexml-returns-null.html 

In the scalelite-nginx docker container there is the file /var/bigbluebutton/playback/presentation/0.9.0/lib/writing.js there is a line 'var xmlDoc = xmlhttp.responseXML;' wich returns null. when added 'xmlhttp.overrideMimeType('text/xml');' before 'smlhttp.send()' the issue is resolved.
This takes place on lines 245 and 834.

Would be nice if this gets fixed.

**Comment by jjvanrossum** [comment]
Hi Amal,

Not entirely sure what you mean, but as far as I can tell this is part of scalelte-nginx, it's not a file of the recording that has a fault, but one of the javascripts needed for playback. in scalelite there also is no redirecting, the recordings are played on the scalelite-application. Maybe what you mean is that the playback-scripts are forked (or something like that) from BBB? I've posted an issue there (https://github.com/bigbluebutton/bigbluebutton/issues/13615), but I don't really see how those files are mapped to these?

**Comment by amalrails** [comment]
@jjvanrossum sorry about the confusion. Can you try the systemd deployment and see if its working? Also the scalelite-run has been updated recently can you pull the latest code  from the master branch.

**Comment by jjvanrossum** [comment]
@amalrails I believe it didn't work, I don't see this changed when deployed via systemd.

**Comment by jfederico** [comment]
Thanks for the report @jjvanrossum, so, based on your findings, the issue would have no much to do with SL. The fix is all on BBB.

When that is fixed, there should be a new docker image for [bbb-playback-proxy](https://hub.docker.com/repository/docker/bigbluebutton/bbb-playback-proxy) which project is in [GitHub](https://github.com/bigbluebutton/bbb-playback-proxy), and I presume you are using.

In terms of SL, we would have to release a new version (with no changes), just for building the corresponding scalelite-nginx image. But that's it.

I'll put this on hold to revisit when https://github.com/bigbluebutton/bigbluebutton/issues/13615 is solved.
