### ISSUE TITLE
Recording importer's failed import process does not retry

### ISSUE THREAD

**Issue by amalrails** [blindsidenetworks/scalelite#722]
If a import process in recording importer fails for some reason, the .tar file does not get reprocessed again until the recording_importer service is restarted.

**Comment by defnull** [comment]
Hmm, #723 only solves half of the issue. If the import fails because the tar file is in the middle of being copied to the spool folder, then yes, the patch may help. But in case of other errors (e.g. a temporary database error) the tar file is left unchanged. Listening for file modifications won't help much?
