### ISSUE TITLE
Question about rebuilding records in scalelite.

### ISSUE THREAD

**Issue by dannyplace** [blindsidenetworks/scalelite#739]
Hi there, 

Just a question.  within BBB there are options to rebuild records and so on. In my case i tell BBB to delete the recordings on the BBB node after scalelite has processed the recordings. 

Are there options within scalelite to let's say "rebuild records"?

**Comment by farhatahmad** [comment]
No this isn't possible. Scalelite simply "stores" the recording, but has no knowledge of how these recordings are processed on the BigBlueButton side. 

They are however, stored in the same format, so you may be able to copy the file off the shared drive back onto the BigBlueButton server (the same place it was deleted from) and seeing if you could rebuild it then

**Comment by jfederico** [comment]
Just to add to what Ahmad already said. In order to be able to reprocess recordings you need the raw data that is stored in BBB. And you can only reprocess it with the scripts included in BBB. So, there are several possible scenarios:

1. you are deleting recordings from BBB once uploaded to SL, but only the playback itself. So, yes, you can rebuild the recording and that will trigger the upload and your later script for delete will do its thing.
2. you are deleting recordings from BBB once uploaded to SL, but you are deleting everything, including raw data.  So, no, you can not reprocess.

You could back up your raw data (before delete) somewhere else outside BBB but that may become a massive volume of data.

**Comment by dannyplace** [comment]
@farhatahmad @jfederico 

Thank you very much for this information.
