### ISSUE TITLE
Enforce the use of SHA256

### ISSUE THREAD

**Issue by jfederico** [blindsidenetworks/scalelite#810]
**Problem to solve:**

Since [v1.3.1](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.3.1), SL supports SHA256. The issue is that the implementation https://github.com/blindsidenetworks/scalelite/pull/697 allows the use of SHA1 and SHA256 together.

There are cases where the organization requires the strict use of only SHA256 (or even higher). In these cases SL should only accept the one defined.

**Purposed solution:**

Add a way to establish if SL will support multiple SHA algorithms (by default), and if it does not, only work with the one defined.

**Considered alternatives:**

**Additional context:**

**Comment by defnull** [comment]
Some notes here:
* There are setups out there that use multiple algorithms at the same time (e.g. a modern frontend + some monitoring clients). Disabling auto.detection is a breaking change and should not happen in a patch-release (as in BBB-2.5.7)
* Greenlight currently does not support anything but SHA1 and the issue was closed as wont-fix -> https://github.com/bigbluebutton/greenlight/issues/1650
* The API spec (https://docs.bigbluebutton.org/dev/api.html) only allows SHA1.
* SHA384 or SHA512 do not have a significant security advantage for this use-case. Phasing out SHA1 and enforcing SHA256 is fine, but not in a patch-release and not per default.

**Comment by jfederico** [comment]
Agree from the integration point of view. This is why the proposed solution is `Add a way to establish if SL will support multiple SHA algorithms (by default), , and if it does not, only work with the one defined.`

Note that by default it would have the same behaviour that BBB does right now. 

Now, BBB is moving towards enforcing the use of one and only one checksum algorithm, ideally, these two APIs should be in sync.
