### ISSUE TITLE
Misterys with mod_bigbluebuttonbn 3.0.1

### ISSUE THREAD

**Issue by texh2s00** [blindsidenetworks/scalelite#814]
Using scale lite. With older plugin all records are showing with 3.0.1 some are missing, but in database there are no differences between whose recordings. anyone have same issue? maybe someone have already resolved it? googling for 3 days now. nothing similar.

**Comment by jfederico** [comment]
Have you isolated the problem? Likely the issue is not SL but somehow the way the new version of the plugin works.

- If you use API Mate to getRecordings, and the recordings are still there, the problem has nothing to do with Scalelite
- If a Moodle server with 2.4 is still getting the recordings, it has nothing to do with SL

Contrib 3.0 (same as Moodle Core 4.0) needs cron enabled, otherwise the recordings will never be pulled. You can google moodle recordings in the bbb-dev and bbb-setup groups, it has been explained/discussed there.

You can also search for how to install Moodle 4.0, some of the reasons for the recordings not showing up are also explained there. And lastly Moodle issues have several of them mentioning it.

**Comment by dseral** [comment]
> Using scale lite. With older plugin all records are showing with 3.0.1 some are missing, but in database there are no differences between whose recordings. anyone have same issue? maybe someone have already resolved it? googling for 3 days now. nothing similar.

I fixed this problem like this:
In moodle/mod/bigbluebuttonbn/classes/local/proxy/recording_proxy.php file around line 240
This line :
$xml = self::fetch_endpoint_xml('getRecordings', [$key => implode(',', $ids), 'state' => 'any']);
if its replace with
$xml = self::fetch_endpoint_xml('getRecordings', [$key => implode(',', $ids), 'state' => 'published']);

Problem solved..
However this is temporary solution ...

**Comment by defnull** [comment]
Scalelite not supporting the `state=any` filter was fixed a long time ago -> https://github.com/blindsidenetworks/scalelite/pull/696
Maybe you are running an old release of Scalelite?
