### ISSUE TITLE
scalelite service does not start after a reboot with error "/srv/scalelite is not writable".

### ISSUE THREAD

**Issue by jetchevers** [blindsidenetworks/scalelite#849]
**Describe the bug**

Hi,
After doing a reboot of the VM containing the scalelite server the scalelite services failed with the following error.

`/srv/scalelite` is not writable.

the permissions of the /srv directory are root:root 755, I tried to change them to 777 but when starting the service it returns to 755.

Any suggestions on how to solve this problem.
Thanks.

**To Reproduce**

***Deployment:***
1. Deployment: Default  Systemd deployment
2. Versions:  V1
3. Tools used for reproducing the issue: 

***Steps to reproduce the behavior:***

1. The system works fine
2. reboot the system.
3. scalelite-api-server fails to update image due to timeout.
4.  pull down the docker image manually with the command "/usr/bin/docker pull blindsidenetwks/scalelite:v1-api"
5.  I comment in the "scalelite-api.service" file where it pulls the image.
6.  system reboot
7. See error
Observation: Last update of the images was 6 days ago.

**Additional context**

#### SO 
Ubuntu 18.04.4 LTS

#### Docker images: 
blindsidenetwks/scalelite   v1-poller               5c615f213338
blindsidenetwks/scalelite   v1-api                  44b806918522
blindsidenetwks/scalelite   v1-recording-importer   eea0c09065bf
blindsidenetwks/scalelite   v1-nginx                aee6d3bae1dc

####  Docker version
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by jfederico** [comment]
It seems to me that this issue is related to #845, it should be solved in release `v1.3.5.2`

Based on your script, you can restart your container once the image is built.

NOW, a big warning (and this is the reason why many people was affected by this bug). For production I would recommend you not to use the `v1` tag, in the same way I would recommend no to use a `latest` tag on any of the docker image components.

This is because in this case the tag `v1` acts as `latest`. While this may bring you some benefits such as an automated update, You don;t even know what version is the one you are running. 

I would encourage you to use the tag for the specific version you want to install. For example `v1.3.5.2`.

This gives you some certainty that no matter what, if you restart the machine or the containers, your application stays running. And you upgrade only when you want to the specific version you want. 

There are a couple other things you may want to do such as having an staging environment where you try the versions before rolling them out.

Let us know how it goes

**Comment by jetchevers** [comment]
Hello Federico
Thanks for your answer.
Modify in the file **/etc/default/scalelite** the variable
**SCALELITE_TAG** to the version it had before the reboot and everything works fine. I will leave the update for the summer break where the server has no load.
I congratulate you for the excellent product you have developed.
Thank you..
Juan.-
