### ISSUE TITLE
With suggested steps in "Setting up a shared volume for recordings", BBB servers cannot write to spool: "permission denied"

### ISSUE THREAD

**Issue by rabser** [blindsidenetworks/scalelite#90]
I'm not completely sure that a mistake in my NFS setup can lead to the problem, but following the steps in the documentation, the BBB server got "permission denied" when executing rsync against NFS mount in scalelite_post_publish.rb.
After some checks i found that scalelite_post_publish.rb should be executed with scalelite-spool as PRIMARY group, or the directory/file creation fails.
I hacked scalelite_post_publish.rb to do this by using the linux command "sg" which execute a command with the primary group changed and the publish copy to scalelite works.

The following are the relevant changed/added lines.

```
  extra_rsync_string = extra_rsync_opts.join(' ') 
  puts("Adding extra rsync options:  #{extra_rsync_string} ")

  puts("Transferring recording archive to #{spool_dir}")
  system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
    || raise('Failed to transfer recording archive')
```

**Comment by jfederico** [comment]
Thanks @rabser

**Comment by secretreal26** [comment]
Hi @rabser ,

Could you please give details about changed and added lines ? These are all new lines ?

These section like this ?
extra_rsync_opts = scalelite_props['extra_rsync_opts'] || []
extra_rsync_string = extra_rsync_opts.join(' ') 
puts("Adding extra rsync options:  #{extra_rsync_string} ")

And do we need to remove :
  system('rsync', '--verbose', '--protect-args', *extra_rsync_opts, archive_file, spool_dir) \
    || raise('Failed to transfer recording archive')


Thanks,

**Comment by ichdasich** [comment]
just got hit by this as well; Should probably be patched upstream.

**Comment by fcasals** [comment]
hello there! it seem that i'm facing the same issue.
I have the spool directory (at the NFS) full of .tar files that corresponds to every record processed by each node. is there a way to move all those recordings from spool to published/presentation folder and update the database at the same time? at this point the recordings are no longer available on the bbb nodes

thanks in advance

**Comment by ichdasich** [comment]
@fcasals different problem. This bug describes an issue where the recordings would not even make it to the spool folder. You should check if the recording-importer container is running, and if so, what its logs say; As soon as that container starts doing its job, it will start to get the recordings out of spool.

**Comment by amg-web** [comment]
chmod +x scalelite_post_publish.rb

**Comment by mmomasters** [comment]
Great solution! Thx!

**Comment by rexon07** [comment]
> I'm not completely sure that a mistake in my NFS setup can lead to the problem, but following the steps in the documentation, the BBB server got "permission denied" when executing rsync against NFS mount in scalelite_post_publish.rb.
> After some checks i found that scalelite_post_publish.rb should be executed with scalelite-spool as PRIMARY group, or the directory/file creation fails.
> I hacked scalelite_post_publish.rb to do this by using the linux command "sg" which execute a command with the primary group changed and the publish copy to scalelite works.
> 
> The following are the relevant changed/added lines.
> 
> ```
>   extra_rsync_string = extra_rsync_opts.join(' ') 
>   puts("Adding extra rsync options:  #{extra_rsync_string} ")
> 
>   puts("Transferring recording archive to #{spool_dir}")
>   system('sg','scalelite-spool', '-c', "rsync --verbose --protect-args #{extra_rsync_string} #{archive_file} #{spool_dir}") \
>     || raise('Failed to transfer recording archive')
> ```

@rabser  i have added this code as well still getting permission denied error .. i see that you have suggested somthing about primary group change. can you elaborate it. Thnaks

**Comment by andrekutianski** [comment]
works like a charm.

**Comment by EmmyGraugans** [comment]
This problem still persists, also with Ubuntu 18.04 and bbb2.3 – the solution with `sg` is a good one and should be incorporated in the provided `scalelite_post_publish.rb`. The other "solutions" to this problem suggested changing the uid and/or gid in the scalelite container (then with different nfs-group and user), but that won't work reliably, since the uid of the user "bigbluebutton" on the BBB-servers isn't stable.

A good addition would be however to add gid=2000 as an *additional* group to the scalelite user in the docker-container. That would allow still for a little more flexibility in setting up NFS-permissions. Especially since the recording-importer needs to be able to read *and delete* the transferred recordings.

**Comment by jfederico** [comment]
@emamirazavi I haven't seen this issue. But we had another report of someone who run into the same issue and the last version includes exactly what you suggested https://github.com/blindsidenetworks/scalelite/commit/0af3674a6be1333ceb7c8ec1d73fadc147ca8bf5
Can you validate the results.

The other change we have recommended before it to add some parameters to rsync. The option has always been there, but it was not documented. No it is mentioned in the README
```
# Extra rsync options for keeping the permissions of the copied files as defined for the directories.
# extra_rsync_opts: ["-av", "--no-owner", "--chmod=F664"]
```

**Comment by EmmyGraugans** [comment]
You can leave this ticket closed, just commenting on the fact that the problem persists for me and I had (still have) to use the additional lines from the first post in this issue.

I tried just this weekend if the new version of the post_publish and recording_importer would work without that "hack", but at least for me it doesn't. It may have to do with our specific NFS setup, but it's just not enough, if a secondary group of the writing process has access to the NFS-folder, it must be the primary group or the user. Since the user "bigbluebutton" doesn't have a fixed uid, it must be written as the group 2000, so the sg has to remain. 

For me. 
YMMV. ;)
