### ISSUE TITLE
Protected recording not working in v1.5.1.x

### ISSUE THREAD

**Issue by relecand** [blindsidenetworks/scalelite#983]
**Describe the bug**
The protected recording feature does not work in Scalelite v1.5.1.2 - all recordings can be accessed via playback link https://SCALELITEURL/playback/presentation/2.3/571d7dee560cb3b8a5604c420285-12222

**To Reproduce**

1. Activate protection features in /etc/default/scalelite

```
PROTECTED_RECORDINGS_ENABLED=true
PROTECTED_RECORDINGS_TOKEN_TIMEOUT=60
PROTECTED_RECORDINGS_TIMEOUT=360
```

`systemctl restart scalelite.target`

2. Open a recording via moodle bbb room. Copy the URL

3. Open the url in a private tab or another browser: the playback will show up (instead of a 404).

***Deployment:***

Version: Scalelite v1.5.1.2 

***Workaround:***

Downgrade Scalelite to v1.3.5.2

**Comment by Ithanil** [comment]
Using GL(v2) with SL 1.5.1.2 I don't see this issue. Protected recording links work as expected. However, my links look as follows: https://SL-URL/recording/ID-XYZ/presentation?token=TOKEN

**Comment by relecand** [comment]
Thanks for your feedback. I checked it with moodle. There I got this URL-format: https://scaleliteurl/playback/presentation/2.3/571d7dee560cb3b8a5604c420285-12222

**Comment by farhatahmad** [comment]
Can you make a `getRecordings` call to Scalelite using API Mate? I believe Moodle imports the recordings (though I'm not 100% sure) and stores the url. You may need to look at "Resyncing" your recordings some how

**Comment by schrd** [comment]
This is broken in the containers, specifically `blindsidenetwks/scalelite:v1.5.1.2-focal260-alpine-nginx`. There are multiple broken things:

* in `/etc/bigbluebutton/nginx/presentation.nginx` the location entries for `/playback/presentation` and `/presentation` need to be removed as they prevent the forwarding of the request to scalelite and deliver the files directly from the filesystem instead
* For the video format the requests are directed to `/playback/video/:recording_id/`. These locations are cought by `/etc/bigbluebutton/nginx/playback-video.nginx` which means that they are served by nginx. If this file is removed, video files won't be served at all because there is no route in scalelite which sends them to the `playback#resource` action.

I think that #916 and #918 are wrong and broke protected recordings.

**Comment by schrd** [comment]
The following changes would fix this:

Replace `/etc/bigbluebutton/nginx/playback-video.nginx` with
```
location ~ "/playback/video/(.*)$" {
	return 307 /video/$1;
}
```

Replace `/etc/bigbluebutton/nginx/presentation.nginx` with
```
location /playback/presentation/playback.html {
        return 301 /playback/presentation/0.81/playback.html?$query_string;
        # If you have recordings from 0.9.0 beta versions and are sure
        # that you will never want to play recordings made with
        # BigBlueButton 0.81, comment the line above and uncomment the
        # following line:
        #return 301 /playback/presentation/0.9.0/playback.html?$query_string;
}

location /playback/presentation/2.0/playback.html {
        return 301 /playback/presentation/2.3/$arg_meetingId?$query_string;
}
```

**Comment by relecand** [comment]
See here: https://github.com/blindsidenetworks/scalelite/issues/1008#issuecomment-1923757343 - still a problem in all new versions of moodle, scalelite and bbb

**Comment by amg-web** [comment]
actually record can be accessed by direct link starting from v.1.4.2
